/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.GestionPatient;
import controleur.GestionRV;
import controleur.Utiles;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modele.Patient;
import modele.RV;

/**
 *
 * @author pc
 */
public class AccueilMedecin extends javax.swing.JFrame {

    public DefaultTableModel dtm = null;
    
    
    /**
     * Creates new form AccueilMedecin
     */
    public AccueilMedecin() {
        initComponents();
        jButton7.setEnabled(false);
    }
    
    public void activerChampsRV() {
        jTextField3.setEnabled(true);
        jButton3.setEnabled(true);
        jTextField4.setEnabled(true);
        jButton4.setEnabled(true);
        jSpinner1.setEnabled(true);
        jSpinner2.setEnabled(true);
        jSpinner3.setEnabled(true);
        jButton5.setEnabled(true);
                
    }
    
    public void desactiverChampsRV() {
        jTextField3.setEnabled(false);
        jButton3.setEnabled(false);
        jTextField4.setEnabled(false);
        jButton4.setEnabled(false);
        jSpinner1.setEnabled(false);
        jSpinner2.setEnabled(false);
        jSpinner3.setEnabled(false);
        jButton5.setEnabled(false);
    }
    
    public void remplirTableauPatients() {
        dtm = new DefaultTableModel();
        
        //ajout des colonnes
        dtm.addColumn("codeP");dtm.addColumn("prenom");dtm.addColumn("nom");dtm.addColumn("age");dtm.addColumn("sexe");dtm.addColumn("adresse");dtm.addColumn("tel");
        
        //relation entre le tableau virtuel et le jtable
        jTable1.setModel(dtm);
    
        GestionPatient gp = new GestionPatient();
        ResultSet rs = gp.listerPatients();
        
        try {
            //parcourir le tableau            
            while(rs.next()) {
                int a = rs.getInt("codeP");
                String b = rs.getString("prenom");
                String c = rs.getString("nom");
                int d = rs.getInt("age");
                String e = rs.getString("sexe");
                String f = rs.getString("adresse");
                int g = rs.getInt("tel");
                
                Object ob[] = {a,b,c,d,e,f,g};
                dtm.addRow(ob);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AccueilMedecin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public void remplirTableauRV() {
        dtm = new DefaultTableModel();
        
        //ajout des colonnes
        dtm.addColumn("id");dtm.addColumn("date");dtm.addColumn("heure");dtm.addColumn("motif");dtm.addColumn("codeP");dtm.addColumn("prenomP");dtm.addColumn("nomP");dtm.addColumn("matricule");dtm.addColumn("prenomM");dtm.addColumn("nomM");
        
        //relation entre le tableau virtuel et le jtable
        jTable2.setModel(dtm);
    
        GestionRV grv = new GestionRV();
        ResultSet rs = grv.listerRVs();
        
        try {
            //parcourir le tableau            
            while(rs.next()) {
                int a = rs.getInt("id");
                String b = rs.getString("date");
                String c = rs.getString("heure");
                String d = rs.getString("motif");
                int e = rs.getInt("codeP");
                String f = rs.getString("prenomP");
                String g = rs.getString("nomP");
                int h = rs.getInt("matricule");
                String i = rs.getString("prenomM");
                String j = rs.getString("nomM");
                
                Object ob[] = {a,Utiles.toDisplayedDate(b),c,d,e,f,g,h,i,j};
                dtm.addRow(ob);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AccueilMedecin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("ID:");

        jButton2.setText("Rechercher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Recherche par id", jPanel3);

        jLabel1.setText("Nom:");

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Recherche par nom du patient", jPanel4);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "codeP", "prenom", "nom", "age", "sexe", "adresse", "tel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton8.setText("Reinitialiser");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Gestion Patients", jPanel1);

        jLabel3.setText("ID:");

        jButton3.setText("Rechercher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(763, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Rechercher par id", jPanel5);

        jLabel4.setText("Nom:");

        jButton4.setText("Rechercher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(684, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Rechercher par nom patient", jPanel7);

        jLabel5.setText("Date de rendez-vous (jj/mm/aaaa):");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(2022, 2022, 2050, 1));

        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(563, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Rechercher par date de Rendez-Vous", jPanel8);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "date", "heure", "motif", "codeP", "prenomP", "nomP", "matricule", "prenomM", "nomM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton6.setText("Reinitialiser");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Annuler");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Gestion Rendez-Vous", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //BOUTON REINITIALISER
        
        //reactiver les champs
        activerChampsRV();
        
        //effacer les champs de saisie
        jTextField3.setText("");
        jTextField4.setText("");
        jSpinner1.setValue(1);
        jSpinner2.setValue(1);
        jSpinner3.setValue(2022);
        
        //remplir le tableau
        remplirTableauRV();
        
        //desactiver bouton annuler
        jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //BOUTON DE RECHERCHE DE PATIENT PAR ID
        jTextField1.setText("");        
        Patient p = null;
        
        int id = Integer.parseInt(jTextField2.getText());
        
        GestionPatient gp = new GestionPatient();
        p = gp.rechercherPatient(id);
        if(p != null) {
            dtm = new DefaultTableModel();
            
            //ajout des colonnes
            dtm.addColumn("codeP");dtm.addColumn("prenom");dtm.addColumn("nom");dtm.addColumn("age");dtm.addColumn("sexe");dtm.addColumn("adresse");dtm.addColumn("tel");
            
            jTable1.setModel(dtm);
            
            int a = p.getCodeP();
            String b = p.getPrenom();
            String c = p.getNom();
            int d = p.getAge();
            String e = p.getSexe();
            String f = p.getAdresse();
            int g = p.getTel();
            
            Object ob[] = {a,b,c,d,e,f,g};
            dtm.addRow(ob);
        } else {
            JOptionPane.showMessageDialog(null, "Ce code patient n'existe pas.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        remplirTableauPatients();
        remplirTableauRV();
    }//GEN-LAST:event_formWindowOpened

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //VIDER LES CHAMPS
        jTextField2.setText("");
        jTextField1.setText("");
        
        //remplir le tableau
        remplirTableauPatients();
               
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //recherche par nom patient        
        jTextField2.setText("");
        String nom = jTextField1.getText();
                
        ResultSet rs = null;
        
        GestionPatient gp = new GestionPatient();
        rs = gp.rechercherPatients(nom);
        
        try {
            if(rs.next()) {
                rs.beforeFirst();
                dtm = new DefaultTableModel();
                dtm.addColumn("codeP");dtm.addColumn("prenom");dtm.addColumn("nom");dtm.addColumn("age");dtm.addColumn("sexe");dtm.addColumn("adresse");dtm.addColumn("tel");
        
                jTable1.setModel(dtm);
                try {                    
                    while(rs.next()) {
                        int a = rs.getInt("codeP");
                        String b = rs.getString("prenom");
                        String c = rs.getString("nom");
                        int d = rs.getInt("age");
                        String e = rs.getString("sexe");
                        String f = rs.getString("adresse");
                        int g = rs.getInt("tel");
                        
                        Object ob[] = {a,b,c,d,e,f,g};
                        dtm.addRow(ob);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AccueilMedecin.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Aucun patient trouve");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AccueilMedecin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //RECHERCHE PAR DATE DE RENDEZ-VOUS
        
        GestionRV grv = new GestionRV();
        ResultSet rs = null;
        String chaineDate = "";
        //recup les donnees
        int jour = Integer.parseInt(jSpinner1.getValue().toString());
        int mois = Integer.parseInt(jSpinner2.getValue().toString());
        int annee = Integer.parseInt(jSpinner3.getValue().toString());
        
        //valider la date
               
        if(Utiles.dateValide(annee, mois, jour)) {
            //si date valide
            chaineDate = Utiles.formaterDate(annee, mois, jour);
            rs = grv.rechercherDateRV(chaineDate);
            
            try {
                if(rs.next()) {
                    dtm = new DefaultTableModel();
                    dtm.addColumn("id");dtm.addColumn("date");dtm.addColumn("heure");dtm.addColumn("motif");dtm.addColumn("codeP");dtm.addColumn("prenomP");dtm.addColumn("nomP");dtm.addColumn("matricule");dtm.addColumn("prenomM");dtm.addColumn("nomM");
                    
                    jTable2.setModel(dtm);
                    
                    rs.beforeFirst();
                    while(rs.next()) {
                        //si resultats remplir le tableau avec les resultats
                        
                        //id,date,heure,motif,codeP,prenomP,nomP,matricule,prenomM,nomM
                        int id = rs.getInt("id");
                        java.sql.Date date = rs.getDate("date");
                        java.sql.Time heure = rs.getTime("heure");
                        String dateD = date.toString();
                        String heureH = heure.toString();
                        String motif = rs.getString("motif");
                        int codeP = rs.getInt("codeP");
                        String prenomP = rs.getString("prenomP");
                        String nomP = rs.getString("nomP");
                        int matricule = rs.getInt("matricule");
                        String prenomM = rs.getString("prenomM");
                        String nomM = rs.getString("nomM");
                        
                        Object ob[] = {id,Utiles.toDisplayedDateRS(dateD),Utiles.toDisplayedTimeRs(heureH),motif,codeP,prenomP,nomP,matricule,prenomM,nomM};
                        dtm.addRow(ob);
                                                
                        //DEBUGGING
                        System.out.println(jour);
                        
                        System.out.println(heure.toString());
                    }
                    //desactiver inputs sauf init
                    //enable annuler
                    jTextField3.setEnabled(false);
                    jButton3.setEnabled(false);
                    jTextField4.setEnabled(false);
                    jButton4.setEnabled(false);
                    jSpinner1.setEnabled(false);
                    jSpinner2.setEnabled(false);
                    jSpinner3.setEnabled(false);
                    jButton5.setEnabled(false);
                    
                    jButton7.setEnabled(true);
                    
                } else {
                    //si pas de resultats
                    JOptionPane.showMessageDialog(null, "Aucun resultat pour cette date");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AccueilMedecin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //si non, JOP(date invalide)
            JOptionPane.showMessageDialog(null, "Date Invalide");            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //RECHERCHER RV PAR ID        
        int id = Integer.parseInt(jTextField3.getText());
        
        //vider les autres champs
        jTextField4.setText("");
        jSpinner1.setValue(1);
        jSpinner2.setValue(1);
        jSpinner3.setValue(2022);
        
        //effectuer recherche
        ResultSet rs = null;
        GestionRV grv = new GestionRV();
        rs = grv.rechercherRV(id);
              
        //recuperer et afficher
        try {
            if(rs.first()) {
                //si resultat
                //mise en place du tableau
                dtm = new DefaultTableModel();
                dtm.addColumn("id");dtm.addColumn("date");dtm.addColumn("heure");dtm.addColumn("motif");dtm.addColumn("codeP");dtm.addColumn("prenomP");dtm.addColumn("nomP");dtm.addColumn("matricule");dtm.addColumn("prenomM");dtm.addColumn("nomM");
                jTable2.setModel(dtm);
                
                //collecte et affichage
                int idRV = rs.getInt("id");
                String date = rs.getString("date");
                String heure = rs.getString("heure");
                String motif = rs.getString("motif");
                int codeP = rs.getInt("codeP");
                String prenomP = rs.getString("prenomP");
                String nomP = rs.getString("nomP");
                int matricule = rs.getInt("matricule");
                String prenomM = rs.getString("prenomM");
                String nomM = rs.getString("nomM");
                
                Object ob[] = {idRV, Utiles.toDisplayedDate(date), heure, motif, codeP, prenomP, nomP, matricule, prenomM, nomM};
                dtm.addRow(ob);
                
                //activer le bouton annuler
                jButton7.setEnabled(true);
                
                //desactiver les autres champs
                desactiverChampsRV();
                
            } else {
                JOptionPane.showMessageDialog(null, "Cet identifiant n'existe pas");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AccueilMedecin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        //RECHERCHER RV PAR NOM
        ResultSet rs = null;
        
        //recuperer la valeur
        String nom = jTextField4.getText();        
        
        //vider les autres champs
        jTextField3.setText("");
        jSpinner1.setValue(1);
        jSpinner2.setValue(1);
        jSpinner3.setValue(2022);        
        
        //recherche
            //si trouve afficher sinon JOp.
        GestionRV grv = new GestionRV();
        rs = grv.rechercherRV(nom);       
        
        try {
            //s'il y a qqch
            if(rs.next()) {
                dtm = new DefaultTableModel();
                dtm.addColumn("id");dtm.addColumn("date");dtm.addColumn("heure");dtm.addColumn("motif");dtm.addColumn("codeP");dtm.addColumn("prenomP");dtm.addColumn("nomP");dtm.addColumn("matricule");dtm.addColumn("prenomM");dtm.addColumn("nomM");
                jTable2.setModel(dtm);        
                rs.beforeFirst();
                try {
                    while(rs.next()) {
                        int idRV = rs.getInt("id");
                        String date = rs.getString("date");
                        String heure = rs.getString("heure");
                        String motif = rs.getString("motif");
                        int codeP = rs.getInt("codeP");
                        String prenomP = rs.getString("prenomP");
                        String nomP = rs.getString("nomP");
                        int matricule = rs.getInt("matricule");
                        String prenomM = rs.getString("prenomM");
                        String nomM = rs.getString("nomM");
                        
                        Object ob[] = {idRV, Utiles.toDisplayedDate(date), heure, motif, codeP, prenomP, nomP, matricule, prenomM, nomM};
                        dtm.addRow(ob);
                        
                    }
                    
                    //activer le bouton annuler
                    jButton7.setEnabled(true);
                        
                    //desactiver les autres champs
                    desactiverChampsRV();
                } catch (SQLException ex) {
                    Logger.getLogger(AccueilMedecin.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Aucun Resultat.");
            }        
        } catch (SQLException ex) {
            Logger.getLogger(AccueilMedecin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //ANNULER UN OU DES RDV
        GestionRV grv = new GestionRV();
        int i=0, nbLignes = dtm.getRowCount();
        
        
        if(nbLignes > 0) {
            int choix = JOptionPane.showConfirmDialog(null, "Etes vous sur de vouloir annuler ces rendez-vous?", "Confirmer?", JOptionPane.YES_NO_OPTION);
            
            if(choix == JOptionPane.YES_OPTION) {
                while(i < nbLignes) {
                    int id = Integer.parseInt(dtm.getValueAt(i, 0).toString());
                    grv.annulerRV(id);
                    i++;
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Aucun rendez-vous a annuler");
        }
        
        //mettre a jour le tableau
        remplirTableauRV();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilMedecin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
